// Licensed to Cloudera, Inc. under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  Cloudera, Inc. licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package com.cloudera.csd.descriptors.parameters;

/**
 * Interface to represent a provided parameter in CSD.
 * <p>
 * A provided parameter just references the parameter by
 * its template name, which is defined by one of the
 * subclasses of {@link Parameter}.
 * <p>
 * It should only be used for parameters automatically
 * generated by the CSD framework. Defining a
 * ProvidedParameter may be necessary for references to
 * those parameters to pass CSD validation. In other
 * cases, like SSL configs, we're able to add the
 * parameters to the validator automatically.
 */
public interface ProvidedParameter extends BasicParameter {
}
